
version: '3.1'

services:
  dailyapp:
    container_name: blog_react
    image: blog_react
    restart: always
    build: ./
    ports:
      - "4444:4444"
    environment:
      - spring.datasource.url= jdbc:mysql://mysqldb:3306/blog?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    networks:
      - springmysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    ports:
      - 3307:3306
    expose:
      - "3306"

    networks:
      - springmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=hamit
      - MYSQL_PASSWORD=root
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"
    restart: unless-stopped
networks:
  springmysql:
    name: springmysql
    driver: bridge